### ISSUE TITLE
How to solve this error2 ?

### ISSUE THREAD

**Issue by kirillportfolio** [hitsoft/docker-drakonhub#3]
admink@LAPTOP-SEVML7S9:~/docker-drakonhub$ docker-compose up
[+] Building 41.3s (6/39)
 => [internal] load build definition from Dockerfile                                                               0.0s
 => => transferring dockerfile: 1.83kB                                                                             0.0s
 => [internal] load .dockerignore                                                                                  0.0s
 => => transferring context: 2B                                                                                    0.0s
 => [internal] load metadata for docker.io/library/ubuntu:20.04                                                   11.8s
 => [ 1/36] FROM docker.io/library/ubuntu:20.04@sha256:626ffe58f6e7566e00254b638eb7e0f3b11d4da9675088f4781a50ae28  0.0s
 => [internal] load build context                                                                                  0.1s
 => => transferring context: 96B                                                                                   0.0s
 => ERROR [ 2/36] RUN apt-get update && apt-get install -y   git   tcl8.6   tk8.6   tcllib   libsqlite3-tcl   li  29.3s
------
 > [ 2/36] RUN apt-get update && apt-get install -y   git   tcl8.6   tk8.6   tcllib   libsqlite3-tcl   libtk-img   unzip   wget   openjdk-14-jre-headless   zip:
#5 1.016 Get:1 http://archive.ubuntu.com/ubuntu focal InRelease [265 kB]
#5 1.022 Get:2 http://security.ubuntu.com/ubuntu focal-security InRelease [114 kB]
#5 1.613 Get:3 http://security.ubuntu.com/ubuntu focal-security/main amd64 Packages [1232 kB]
#5 1.636 Get:4 http://archive.ubuntu.com/ubuntu focal-updates InRelease [114 kB]
#5 1.820 Get:5 http://archive.ubuntu.com/ubuntu focal-backports InRelease [101 kB]
#5 2.016 Get:6 http://archive.ubuntu.com/ubuntu focal/main amd64 Packages [1275 kB]
#5 3.778 Get:7 http://security.ubuntu.com/ubuntu focal-security/universe amd64 Packages [809 kB]
#5 4.018 Get:8 http://archive.ubuntu.com/ubuntu focal/restricted amd64 Packages [33.4 kB]
#5 4.054 Get:9 http://archive.ubuntu.com/ubuntu focal/universe amd64 Packages [11.3 MB]
#5 4.995 Get:10 http://security.ubuntu.com/ubuntu focal-security/multiverse amd64 Packages [30.1 kB]
#5 5.013 Get:11 http://security.ubuntu.com/ubuntu focal-security/restricted amd64 Packages [682 kB]
#5 19.91 Get:12 http://archive.ubuntu.com/ubuntu focal/multiverse amd64 Packages [177 kB]
#5 20.11 Get:13 http://archive.ubuntu.com/ubuntu focal-updates/universe amd64 Packages [1098 kB]
#5 21.86 Get:14 http://archive.ubuntu.com/ubuntu focal-updates/multiverse amd64 Packages [33.3 kB]
#5 21.92 Get:15 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 Packages [1689 kB]
#5 24.44 Get:16 http://archive.ubuntu.com/ubuntu focal-updates/restricted amd64 Packages [738 kB]
#5 25.51 Get:17 http://archive.ubuntu.com/ubuntu focal-backports/universe amd64 Packages [7185 B]
#5 25.52 Get:18 http://archive.ubuntu.com/ubuntu focal-backports/main amd64 Packages [2668 B]
#5 25.61 Fetched 19.7 MB in 25s (795 kB/s)
#5 25.61 Reading package lists...
#5 27.36 Reading package lists...
#5 28.80 Building dependency tree...
#5 29.16 Reading state information...
#5 29.22 E: Unable to locate package openjdk-14-jre-headless
------
### failed to solve: rpc error: code = Unknown desc = executor failed running [/bin/sh -c apt-get update && apt-get install -y   git   tcl8.6   tk8.6   tcllib   libsqlite3-tcl   libtk-img   unzip   wget   openjdk-14-jre-headless   zip]: exit code: 100

**Comment by bigale** [comment]
I can't remember how I figured this out but it works for me after doing the following:

In the Dockerfile replace this line: 
openjdk-14-jre-headless \

with this line:
default-jre \

Then I have in my shell history to do the following:
sudo add-apt-repository ppa:openjdk-r/ppa
sudo docker-compose build --no-cache
sudo docker-compose up

Good luck.  Let me know how it goes and maybe I have some links stored or notes and I can dig a little more.

**Comment by smeagol74** [comment]
> sudo add-apt-repository ppa:openjdk-r/ppa

This step is not necessary, but thank you for details. 

I've updated the `Dockerfile` to use the default JRE as you suggested. So now docker should work again.
